### ISSUE TITLE
Issue with typespec that has `when`

### ISSUE THREAD

**Issue by rodrigues** [esl/gradient#23]
The following typespec fails when running `mix gradient`:

```elixir
defmodule Gradissue do
  @spec foo({:a, x}) :: {:a, x} | {:b, x} when x: term()
  def foo({:a, x}) do
    case x do
      :foo ->
        {:a, x}

      _ ->
        {:b, x}
    end
  end
end
```

```shell
❯ mix gradient
Compiling 1 file (.ex)
Typechecking files...
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(2, [{:type, 2, :constraint, [{:atom, 2, :is_subtype}, [{:var, 2, :x}, {:type, 2, :term, []}]]}])
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:765: anonymous fn/1 in Gradient.AstSpecifier.set_form_end_line/3
    (elixir 1.12.2) lib/enum.ex:3856: Enum.find_list/3
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:764: Gradient.AstSpecifier.set_form_end_line/3
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:108: Gradient.AstSpecifier.context_mapper_map/4
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:468: Gradient.AstSpecifier.spec_mapper/3
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:109: Gradient.AstSpecifier.context_mapper_map/4
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:135: Gradient.AstSpecifier.mapper/3
```

**Comment by erszcz** [comment]
Thanks for the report! Keep 'em coming!

**Comment by lud** [comment]
I have this error:

```
** (ArgumentError) errors were found at the given arguments:

  * 2nd argument: not a tuple

    :erlang.element(2, [{:type, 196, :constraint, [{:atom, 196, :is_subtype}, [{:var, 196, :account_id}, {:type, 197, :binary, []}]]}, {:type, 196, :constraint, [{:atom, 196, :is_subtype}, [{:var, 196, :config}, {:type, 197, :map, [{:type, 197, :map_field_exact, [{:atom, 0, :limit}, {:type, 197, :pos_integer, []}]}]}]]}])
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:786: anonymous fn/1 in Gradient.AstSpecifier.set_form_end_line_/3
```

Caused by this bit of code:

```
case Enum.find(forms, fn f ->
           anno = elem(f, 1)
```

The `forms` var:

```
forms: [
  [
    {:type, 196, :constraint,
     [
       {:atom, 196, :is_subtype},
       [{:var, 196, :account_id}, {:type, 197, :binary, []}]
     ]},
    {:type, 196, :constraint,
     [
       {:atom, 196, :is_subtype},
       [
         {:var, 196, :config},
         {:type, 197, :map,
          [
            {:type, 197, :map_field_exact,
             [{:atom, 0, :limit}, {:type, 197, :pos_integer, []}]}
          ]}
       ]
     ]}
  ]
]
```

And the typespec:

```
  @spec partition_accounts_for_max_limit([{account_id, config}], integer) :: [
          {account_id, config}
        ]
        when account_id: binary, config: %{limit: pos_integer()}
```

**Comment by erszcz** [comment]
Thanks for confirming, @lud!

**Comment by erszcz** [comment]
@rodrigues @lud Thanks again for your reports! This should be fixed now :+1:
