### ISSUE TITLE
Gradient crashes violently while analysing file that implements protocols

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [esl/gradient#44]
Background
-------------

I have created an file that represents an `Option` type in Elixir (aka, Maybe Monad). This is for learning purposes and the code works and runs as expected (as least as far as I can tell). 

Problem
-----------

However when I try to run `mix gradient`, the tool crashes:

**logs**
```
$ mix gradient
Compiling 1 file (.ex)
Generated grokking_fp app
Typechecking files...
** (MatchError) no match of right hand side value: :error
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:194: Gradient.AstSpecifier.mapper/3
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:122: Gradient.AstSpecifier.context_mapper_fold/4
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:148: Gradient.AstSpecifier.mapper/3
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:122: Gradient.AstSpecifier.context_mapper_fold/4
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:123: Gradient.AstSpecifier.context_mapper_fold/4
    (gradient 0.1.0) lib/gradient/ast_specifier.ex:93: Gradient.AstSpecifier.run_mappers/2
    (gradient 0.1.0) lib/gradient.ex:26: Gradient.type_check_file/2
    (elixir 1.13.2) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
```

Expected behaviour
---------------------

It may very well be that my type specs are incorrect, even though Dialzyer does not complain (and it usually does when typespecs are a mess). But even in such a scenario, I would expect gradient to tell me "Typespec A is not well defined" or something instead of crashing.

**option.ex**
```elixir
defmodule Option do
  @type t(elem) :: Option.Some.t(elem) | Option.None.t()

  defmodule Some do
    @type t(elem) :: %__MODULE__{val: elem}

    defstruct [:val]

    defimpl Collectable do
      @impl Collectable
      def into(option), do: {option, fn acc, _command -> {:done, acc} end}
    end

    defimpl Enumerable do
      @impl Enumerable
      def count(_some), do: {:ok, 1}

      @impl Enumerable
      def member?(some, element), do: {:ok, some.val == element}

      @impl Enumerable
      def reduce(some, acc, fun)

      def reduce(_some, {:halt, acc}, _fun), do: {:halted, acc}
      def reduce(some, {:suspend, acc}, fun), do: {:suspended, acc, &reduce(some, &1, fun)}
      def reduce([], {:cont, acc}, _fun), do: {:done, acc}

      def reduce(%Option.Some{} = some, {:cont, acc}, fun),
        do: reduce([], fun.(some.val, acc), fun)

      @impl Enumerable
      def slice(_option), do: {:error, __MODULE__}
    end
  end

  defmodule None do
    @type t :: %__MODULE__{}

    defstruct []

    defimpl Collectable do
      @impl Collectable
      def into(option) do
        {option,
         fn
           _acc, {:cont, val} ->
             %Option.Some{val: val}

           acc, :done ->
             acc

           _acc, :halt ->
             :ok
         end}
      end
    end

    defimpl Enumerable do
      @impl Enumerable
      def count(_none), do: {:error, __MODULE__}

      @impl Enumerable
      def member?(_none, _element), do: {:error, __MODULE__}

      @impl Enumerable
      def reduce(none, acc, fun)

      def reduce(_none, {:cont, acc}, _fun), do: {:done, acc}
      def reduce(_none, {:halt, acc}, _fun), do: {:halted, acc}
      def reduce(none, {:suspend, acc}, fun), do: {:suspended, acc, &reduce(none, &1, fun)}

      @impl Enumerable
      def slice(_option), do: {:error, __MODULE__}
    end
  end

  @spec new(any) :: %Option.Some{val: any}
  def new(val), do: %__MODULE__.Some{val: val}

  @spec new :: %Option.None{}
  def new, do: %__MODULE__.None{}
end
```

When I delete this file, gradient works normally.

**Comment by stevensonmt** [comment]
Have you tried commenting out the protocol implementations and then adding them back one by one to see which is actually tripping Gradient up?

**Comment by Fl4m3Ph03n1x** [comment]
My protocol implementations obey the official spec. Nonetheless it is an exercise worth doing. Will report tomorrow once I get near my work setup .

**Comment by Fl4m3Ph03n1x** [comment]
I decided to delete the `_build` folder, and manually delete the `mix.lock` and `deps` folder. Turns out something there was amiss, thus causing the crash. 

To be clear, gradient does not crash now, but the output it gives still has some issues. 
I will create a new ticket for this, as the nature of the problem has changes. 

I will be closing this one.
