### ISSUE TITLE
Unable to run Gradient with latest changes: Erlang error: {:noproc, {:gen_server, :call,

### ISSUE THREAD

**Issue by eksperimental** [esl/gradient#81]
I'm  runnning on this project/commit
https://github.com/eksperimental/checker_basic/tree/bd2bcbe717863c4a1c0c7acc1866072815608e52

`mix gradient` give me

```
Generated checker app
Typechecking files...
** (ErlangError) Erlang error: {:noproc, {:gen_server, :call, [:gradualizer_db, {:get_spec, :erlang, :get_module_info, 2}, 5000]}}
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/eksperimental/checker_basic/deps/gradualizer/src/typechecker.erl:4985: :typechecker.type_check_form_with_timeout({:function, 0, :__info__, 1, [{:clause, 0, [{:atom, 0, :module}], [], [{:atom, 0, Checker.Application}]}, {:clause, 0, [{:atom, 0, :functions}], [], [{:cons, 0, {:tuple, 0, [{:atom, 0, :start}, {:integer, 0, 2}]}, {:cons, 0, {:tuple, 0, [{:atom, 0, :stop}, {:integer, 0, 1}]}, {nil, 0}}}]}, {:clause, 0, [{:atom, 0, :macros}], [], [nil: 0]}, {:clause, 0, [{:atom, 0, :exports_md5}], [], [{:bin, 0, [{:bin_element, 0, {:string, 0, [250, 165, 114, 93, 168, 241, 30, 158, 117, 40, 133, 192, 247, 244, 156, 211]}, :default, :default}]}]}, {:clause, 0, [{:match, 0, {:var, 0, :Key}, {:atom, 0, :attributes}}], [], [{:call, 0, {:remote, 0, {:atom, 0, :erlang}, {:atom, 0, :get_module_info}}, [{:atom, 0, Checker.Application}, {:var, 0, :Key}]}]}, {:clause, 0, [{:match, 0, {:var, 0, :Key}, {:atom, 0, :compile}}], [], [{:call, 0, {:remote, 0, {:atom, 0, :erlang}, {:atom, 0, :get_module_info}}, [{:atom, 0, Checker.Application}, {:var, 0, :Key}]}]}, {:clause, 0, [{:match, 0, {:var, 0, :Key}, {:atom, 0, :md5}}], [], [{:call, 0, {:remote, 0, {:atom, 0, :erlang}, {:atom, 0, :get_module_info}}, [{:atom, 0, Checker.Application}, {:var, 0, :Key}]}]}, {:clause, 0, [{:atom, 0, :deprecated}], [], [nil: 0]}]}, [], false, {:env, %{{:__info__, 1} => [{:type, 1, :bounded_fun, [{:type, 1, :fun, [{:type, 1, :product, [{:type, 1, :union, [{:atom, 1, :attributes}, {:atom, 1, :compile}, {:atom, 1, :functions}, {:atom, 1, :macros}, {:atom, 1, :md5}, {:atom, 1, :exports_md5}, {:atom, 1, :module}, {:atom, 1, :deprecated}]}]}, {:type, 1, :any, []}]}, []]}], {:start, 2} => {:type, 0, :any, []}, {:stop, 1} => {:type, 0, :any, []}}, %{}, %{}, %{module: Checker.Application, records: %{}, types: %{}}, false, false, true, [], 30, :none}, [return_errors: true, app_path: nil])
    (stdlib 3.17.1) lists.erl:1280: :lists.foldr/3
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/eksperimental/checker_basic/deps/gradualizer/src/typechecker.erl:4938: :typechecker.type_check_forms/2
    (gradualizer 0.1.3+build.1080.ref9e629ad) /home/eksperimental/checker_basic/deps/gradualizer/src/gradualizer.erl:201: :gradualizer.type_check_forms/3
    (gradient 0.1.0) lib/gradient.ex:55: Gradient.maybe_gradualizer_check/2
    (gradient 0.1.0) lib/gradient.ex:30: Gradient.type_check_file/2
    (elixir 1.13.4) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
    (elixir 1.13.4) lib/enum.ex:4475: Enumerable.List.reduce/3
```

This happens after latest changes Gradient and Gradualizer

**Comment by erszcz** [comment]
Hmmm, I cannot reproduce this problem - log and env info attached: 

```
Typechecking files...
lib/checker/job.ex: The atom on line 824 is expected to have type list(term()) but it has type :none


lib/checker/job.ex: Call to undefined function Checker.Util.uniq_id/0 on line 12
lib/checker/job_supervisor.ex: Call to undefined function Checker.Util.uniq_id/0 on line 8
lib/checker/mock.ex: Undefined remote type Checker.url/0 on line 15
lib/checker/server.ex: Call to undefined function Checker.Util.uniq_id/0 on line 11
lib/checker/server.ex: Call to undefined function Checker.Util.pid/1 on line 126
lib/checker/server.ex: Call to undefined function Checker.terminate/2 on line 202
lib/checker/server_supervisor.ex: Call to undefined function Checker.Util.uniq_id/0 on line 8
lib/checker/util.ex: Undefined remote type Checker.url/0 on line 4
lib/checker/util.ex: The function call on line 33 is expected to have type pos_integer() but it has type integer()
31   @spec uniq_id() :: pos_integer()
32   def uniq_id() do
33     System.unique_integer([:positive, :monotonic])
34   end
35

lib/checker.ex: The spec child_pid/1 on line 126 follows another spec, but only one spec per function clause is allowed
lib/checker.ex: Call to undefined function Checker.Util.child_pid/1 on line 128
lib/checker.ex: Call to undefined function Checker.Util.child_pid/1 on line 136
22:53:56 erszcz @ x6 : ~/work/eksperimental/checker_basic ((bd2bcbe...) %)
$ git st
HEAD detached at bd2bcbe
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.tool-versions

nothing added to commit but untracked files present (use "git add" to track)
22:54:12 erszcz @ x6 : ~/work/eksperimental/checker_basic ((bd2bcbe...) %)
$ git diff
22:54:13 erszcz @ x6 : ~/work/eksperimental/checker_basic ((bd2bcbe...) %)
$ asdf current erlang
erlang          24.0.5          /Users/erszcz/.tool-versions
a22:54:26 erszcz @ x6 : ~/work/eksperimental/checker_basic ((bd2bcbe...) %)
$ asdf current elixir
elixir          1.13.1          /Users/erszcz/work/eksperimental/checker_basic/.tool-versions
```

**Comment by eksperimental** [comment]
my setup is:

```
elixir          1.13.4-otp-24
erlang          24.3.3 

```

**Comment by eksperimental** [comment]
I think the issue is related to different erlang versions , changing the versions, at one point it asked to install `hex`, and after that the error was gone.. Now even switching to otp 25, the error disappeared.

**Comment by eksperimental** [comment]
For the record, I think the issue can be solved for running:
`mix local.rebar --force`

**Comment by eksperimental** [comment]
Can someone create a Elixir project, add Gradient and test it with the latest elixir and with latest OTP 24, please?

elixir          1.13.4-otp-24
erlang          24.3.4       

I still see this problem and I have no idea how to solve it.

**Comment by eksperimental** [comment]
I managed to track it to `elixir 1.13.4-otp-24` in asdf.
it does not happend with `elixir 1.13.3-otp-24` or earlier versions.

There are some changes in 1.13.4 related to the Elixir compiler, it is probably that.

**Comment by eksperimental** [comment]
Apparently it was a faulty installation, I uninstalled `elixir 1.13.3-otp-24` and reinstalled it and it works.

**Comment by eksperimental** [comment]
I'm closing this as it didn't happen again.
If anyone gets hits by this, try reinstalling Elixir.
